# Generated by Django 3.2.9 on 2021-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Composer',
                'verbose_name_plural': 'Composers',
            },
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artists', models.ManyToManyField(blank=True, related_name='album', to='composer.Composer')),
            ],
            options={
                'verbose_name': 'Compilation',
                'verbose_name_plural': 'Compilations',
            },
        ),
    ]
