# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 20))
        self.menubar.setObjectName("menubar")
        self.menutest = QtWidgets.QMenu(self.menubar)
        self.menutest.setObjectName("menutest")
        self.menuasda = QtWidgets.QMenu(self.menubar)
        self.menuasda.setObjectName("menuasda")
        self.menuqweqwe = QtWidgets.QMenu(self.menubar)
        self.menuqweqwe.setObjectName("menuqweqwe")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionasdasd = QtWidgets.QAction(MainWindow)
        self.actionasdasd.setObjectName("actionasdasd")
        self.actionadsasd = QtWidgets.QAction(MainWindow)
        self.actionadsasd.setObjectName("actionadsasd")
        self.actionasdasda = QtWidgets.QAction(MainWindow)
        self.actionasdasda.setObjectName("actionasdasda")
        self.actionasdasda_2 = QtWidgets.QAction(MainWindow)
        self.actionasdasda_2.setObjectName("actionasdasda_2")
        self.actionasd = QtWidgets.QAction(MainWindow)
        self.actionasd.setObjectName("actionasd")
        self.actionqweqweqe = QtWidgets.QAction(MainWindow)
        self.actionqweqweqe.setObjectName("actionqweqweqe")
        self.menutest.addAction(self.actionqweqweqe)
        self.menuasda.addAction(self.actionasdasda)
        self.menuasda.addAction(self.actionasdasda_2)
        self.menuasda.addSeparator()
        self.menuasda.addSeparator()
        self.menuasda.addAction(self.actionasd)
        self.menuqweqwe.addAction(self.actionasdasd)
        self.menuqweqwe.addAction(self.actionadsasd)
        self.menubar.addAction(self.menutest.menuAction())
        self.menubar.addAction(self.menuasda.menuAction())
        self.menubar.addAction(self.menuqweqwe.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menutest.setTitle(_translate("MainWindow", "test"))
        self.menuasda.setTitle(_translate("MainWindow", "asda"))
        self.menuqweqwe.setTitle(_translate("MainWindow", "qweqwe"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.actionasdasd.setText(_translate("MainWindow", "asdasd"))
        self.actionadsasd.setText(_translate("MainWindow", "adsasd"))
        self.actionasdasda.setText(_translate("MainWindow", "asdasda"))
        self.actionasdasda_2.setText(_translate("MainWindow", "asdasda"))
        self.actionasd.setText(_translate("MainWindow", "asd"))
        self.actionqweqweqe.setText(_translate("MainWindow", "qweqweqe"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
